### PR TITLE
Feature excel add file picker

### LINKED ISSUE #453: [Excel] Filepicker

### PR DESCRIPTION
**Pull request by Etschbeijer**
closes #453

### CODE REVIEW

**Comment by Etschbeijer** [comment]
Feature was still working, minimal refactoring was done.
Adding description of the function of the feature in following comments

**Comment by Etschbeijer** [comment]
The file picker is a feature that enables you to pick multiple files and add their names to the table.
The feature is located in the excel-swate-nav-bar in the File Picker tab.
The button Pick file names opens a folder view of your computer, so that you can select the file names you need.
grafik

**Comment by Etschbeijer** [comment]
The files you have selected are displayed below the button Pick file names. You can rearrange their order. When you have forgotten one, you have to select the previous ones too, because when you only pick the missing one, the others are gone.

grafik

**Comment by Etschbeijer** [comment]
You can add the selected file names to the table by selecting the cells that the file names shall be put in and press the Insert file names button. You can only select one column at time. 
When you have selected more cells than you have selected file names, only the selected file names will be added and the rest of the cells stay empty.  When you have selected less cells than you have selected file names, the cells will be filles, up to the point, you have more file names than cells.

grafik

**Review by Freymaurer — CHANGES_REQUESTED** [review]
Table displaying selected files should propably be full width. Can you verify this on standalone and adjust it for standalone as well as for excel? 

See: bulma table docs

**Comment by Freymaurer** [comment]
> @Freymaurer Yes, it had full width for both versions. The excel version is displayed in the pictures above your comment.

And in the snd picture in the red box the listed file name elements are not full width

**Pull request merged**
